using System;
using System.Linq;
using System.Drawing;

namespace RandomNumbersGame
{
    internal class Program
    {
        static void Main(string[] args)
        {
            Console.Write("Enter the first (smallest) number: ");
            int firstNumber = int.Parse(Console.ReadLine());
            Console.Write("Enter the second (biggest) number: ");
            int secondNumber = int.Parse(Console.ReadLine());
            Console.Write("Enter your number which must be between the first and second number: ");
            int userNumber = int.Parse(Console.ReadLine());
            PrintNumber(firstNumber, secondNumber, userNumber);
        }

        static void PrintNumber(int firstNumber, int secondNumber, int userNumber)
        {
            bool isValid = true;

            if (userNumber >= secondNumber || userNumber <= firstNumber)
            {
                isValid = false;

                while (isValid == false)
                {
                    Console.WriteLine($"Your input is invalid! Try again with number between {firstNumber} and {secondNumber}");
                    userNumber = int.Parse(Console.ReadLine());
                    if (userNumber < secondNumber || userNumber > firstNumber)
                    {
                        isValid = true;
                    }
                }
            }

            int countOfAttempts = 3;


            Random random = new Random();
            int randomNumber = random.Next(firstNumber, secondNumber);

            while (countOfAttempts != 0)
            {
                if (countOfAttempts != 3)
                {
                    userNumber = int.Parse(Console.ReadLine());
                    if (userNumber > secondNumber || userNumber < firstNumber)
                    {
                        Console.WriteLine($"Your input is invalid! Try again with number between {firstNumber} and {secondNumber}");
                        userNumber = int.Parse(Console.ReadLine());
                    }
                }

                if (userNumber > secondNumber || userNumber < firstNumber)
                {
                    Console.WriteLine($"Your input is invalid! Try again with number between {firstNumber} and {secondNumber}");
                    userNumber = int.Parse(Console.ReadLine());
                }

                if (userNumber != randomNumber)
                {
                    if (true)
                    {
                        countOfAttempts--;
                        if (countOfAttempts == 0)
                        {
                            continue;
                        }
                        Console.WriteLine($"Oh, no! Your number is different than the random number. You have another {countOfAttempts} attempts.");
                    }
                }
                else
                {
                    Console.WriteLine($"Congratulations! Your number is equal to that generated by the console.");
                    Environment.Exit(0);
                }
            }
            Console.WriteLine($"You lost the game! The random number was {randomNumber}. Better luck next time!");
            Environment.Exit(0);
        }
    }
}