using System;
using System.Linq;

namespace SoftUni
{
    class Program
    {
        static void Main(string[] args)
        {
            PrintNumber();
        }

        static void PrintNumber()
        {
            Console.Write("Enter the first number: ");
            int firstNumber = int.Parse(Console.ReadLine());
            Console.Write("Enter the second number: ");
            int secondNumber = int.Parse(Console.ReadLine());
            Console.Write("Enter your number which be must between the first and second number: ");
            int userNumber = int.Parse(Console.ReadLine());

            if (userNumber > secondNumber || userNumber < firstNumber)
            {
                Console.WriteLine($"Your input is invalid! Try again with number between {firstNumber} and {secondNumber}");
                userNumber = int.Parse(Console.ReadLine());
            }

            int countOfAttempts = 3;


            Random random = new Random();
            int randomNumber = random.Next(firstNumber, secondNumber);

            while (countOfAttempts != 0)
            {
                if (countOfAttempts != 3)
                {
                    userNumber = int.Parse(Console.ReadLine());
                    if (userNumber > secondNumber || userNumber < firstNumber)
                    {
                        Console.WriteLine($"Your input is invalid! Try again with number between {firstNumber} and {secondNumber}");
                        userNumber = int.Parse(Console.ReadLine());
                    }
                }

                if (userNumber > secondNumber || userNumber < firstNumber)
                {
                    Console.WriteLine($"Your input is invalid! Try again with number between {firstNumber} and {secondNumber}");
                    userNumber = int.Parse(Console.ReadLine());
                }

                if (userNumber != randomNumber)
                {
                    if (true)
                    {
                        countOfAttempts--;
                        Console.WriteLine($"Oh, no! Your number is different than the random number. You have another {countOfAttempts} attempts.");
                    }
                }
                else
                {
                    Console.WriteLine($"Congratulations! Your number is equal to that generated by the console. Play again?");
                    return;
                }
            }
            Console.WriteLine($"You lost the game! The random number was {randomNumber}. Try again?");
        }
    }
}